global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'airflow-webserver'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['airflow-webserver:8080']

  - job_name: 'airflow-worker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['airflow-worker:8793']

  - job_name: 'airflow-scheduler'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['airflow-scheduler:8793']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']