name: Run Unit Tests

on:
  push:
    branches: [tristan2]
  pull_request:
    branches: [tristan2]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Mise à jour vers v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Mise à jour vers v4
        with:
          python-version: '3.12'  # Spécifiez la version de Python que vous utilisez

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ga.txt
          
      - name: Run Unit Tests
        run: |
          pytest plugins/tests --maxfail=5 --disable-warnings
